### PR TITLE
mapping _id to id

### PR DESCRIPTION
**Pull request by mwielocha**
@marekzebrowski 
Its a little bit controversial, but we wouldn't have to use `_id` in our domain case classes...

### CODE REVIEW

**Comment by marekzebrowski** [comment]
what with `UserToken` - where `_id` is `UUID` not ObjectId ?

**Comment by mwielocha** [comment]
Right, good point, for a second there I thought that docs in mongo can only have _id as ObjectId, so we either need some other way to do this or we should learn to live with _id in the code :/

**Comment by marekzebrowski** [comment]
maybe we can have 2 versions - one with `_id` and other one without? 
We already need to have 2 versions for enums - one for serializing by name and other for serializing by value

**Comment by mwielocha** [comment]
There is also a workaround: you can have a `def id = _id` in the case class but its not the same. With two versions we would have to be careful what we import, right?

**Pull request closed without merging**
